# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
        environment:
          GO111MODULE: "on"
      - image: postgres:11.5-alpine
        environment:
          POSTGRES_USER: sadihakan
          POSTGRES_DB: postgres

    working_directory: /go/src/github.com/sadihakan/dummy-dump
    steps:
      - checkout
      - run: go mod tidy
      - run: sleep 10
      - run: go run ./cmd